"""initial schema

Revision ID: 0441e47cf078
Revises: 
Create Date: 2026-07-23 02:50:25.437908

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0441e47cf078'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scenario', sa.Enum('SALA_DE_AULA', name='scenario_type'), nullable=False),
    sa.Column('persona', sa.Enum('PROFESSOR_RIGOROSO', 'ORIENTADOR_ACOLHEDOR', 'ESPECIALISTA_TECNICO', 'PLATEIA_LEIGA', name='persona_type'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUDIO_RECEIVED', 'PROCESSING', 'COMPLETED', 'FAILED', name='presentation_status'), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('pdf_filename', sa.String(length=255), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('slides_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_status'), 'presentations', ['status'], unique=False)
    op.create_index(op.f('ix_presentations_user_id'), 'presentations', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_analysis', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_presentation_id'), 'feedbacks', ['presentation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_presentation_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_presentations_user_id'), table_name='presentations')
    op.drop_index(op.f('ix_presentations_status'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
