"""auditoria de chamadas de ia (llm_calls)

Revision ID: e8732f4eb5c9
Revises: 76acc52e4337
Create Date: 2026-07-28 14:25:03.436066

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e8732f4eb5c9'
down_revision: str | None = '76acc52e4337'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('presentation_id', sa.UUID(), nullable=False),
    sa.Column('etapa', sa.Enum('STT', 'GERACAO_PERGUNTAS', name='llm_call_stage'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_saida', sa.Integer(), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_etapa'), 'llm_calls', ['etapa'], unique=False)
    op.create_index(op.f('ix_llm_calls_presentation_id'), 'llm_calls', ['presentation_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_sucesso'), 'llm_calls', ['sucesso'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_llm_calls_sucesso'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_presentation_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_etapa'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # `drop_table` não remove o TYPE do Postgres: sem esta linha, um downgrade seguido de
    # upgrade falharia com "type llm_call_stage already exists". O autogenerate não emite
    # isso sozinho.
    sa.Enum(name='llm_call_stage').drop(op.get_bind(), checkfirst=True)
